config/routes.rb
Rails.application.routes.draw do
  resources :pontos
  resources :trocas
  resources :produtos
  resources :clientes do
    member do
      get 'edit_password'
      patch 'update_password'
    end 
  end
  devise_for :funcionarios, path: 'auth'
  resources :funcionarios
  resources :categorias
  root "application#index"

  scope :api, defaults: { format: :json } do
    devise_for :clientes,
      controllers: {
        sessions: 'api/sessions',
        passwords: 'api/passwords'
      }
  end
  namespace :api do
    resources :clientes, only: [:update] do
      member do
        patch 'update_password'
      end
      collection do
        get 'token'
      end
    end
    resources :trocas, only: [:create, :index] do
      member do
        put 'cancelar'
      end
    end
    resources :produtos, only: [:index]
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/cliente.rb
class Cliente < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :jwt_authenticatable, jwt_revocation_strategy: JwtDenylist

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  has_many :pontos
  has_many :trocas

  validates :email, presence: true
  validates :usuario, uniqueness: true
  validates :email, uniqueness: true
  validates :password, presence: true, :length => { :minimum => 6}, :on => :addCliente

  
  def saldo
    self.pontos.sum(:pontos) - self.trocas.where(status: :finalizado).sum(:pontos)
  end

  def saldo_disponivel
    self.pontos.sum(:pontos) - self.trocas.where(status: [:finalizado, :solicitado, :confirmado]).sum(:pontos)
  end

  private
    def self.current=(cliente)
      Thread.current[:current_cliente] = cliente
    end

    def self.current
      Thread.current[:current_cliente]
    end
end

app/controllers/api/clientes_controller.rb
class Api::ClientesController < ApiController
  before_action :set_cliente, only: [:update, :update_password]

  # GET /clientes/token
  def token
    if current_cliente
      render json: current_cliente, methods: [:saldo, :saldo_disponivel]
    else
      render json: nil, status: :unauthorized
    end
  end

  # PATCH/PUT /clientes/1
  def update
    if @cliente.update(cliente_params)
      render json: @cliente, status: :ok
    else
      render json: @cliente.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update_password
    if @cliente.update_with_password(password_params)
      render json: @cliente, status: :ok
    else
      render json: @cliente.errors.full_messages, status: :unprocessable_entity
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cliente_params
    if params[:cliente]
      params.require(:cliente).permit(
        :nome, 
        :email, 
        :usuario
      )
    end
  end

  def password_params
    if params[:cliente]
      params.require(:cliente).permit(
          :current_password,
          :password,
          :password_confirmation
      )
    end
  end

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: %i[ show edit edit_password update update_password destroy ]

  # GET /clientes or /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1 or /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  def edit_password

  end
  

  # POST /clientes or /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: "Cliente was successfully created." }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1 or /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_password
    respond_to do |format|
      if @cliente.update(cliente_params_password)
        format.html { redirect_to @cliente, notice: "Cliente was successfully updated." }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit_password, status: :unprocessable_entity }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1 or /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: "Cliente was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cliente_params
      params.require(:cliente).permit(:nome, :email, :usuario)
    end

    def cliente_params_password
      params.require(:cliente).permit(:password, :password_confirmation)
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :usuario %>
    <%= form.text_field :usuario, class:"form-control" %>
  </div>

  <% unless cliente.persisted? %>

    <div class="field form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class:"form-control" %>
    </div>

  <% end %>

  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>
<br>
<%= link_to 'Show', @cliente, class:"btn btn-primary" %> 
<%= link_to 'Back', clientes_path, class:"btn btn-primary" %>

app/views/clientes/edit_password.html.erb
<h1>Editing Password Cliente</h1>

<%= form_with(model: @cliente) do |form| %>
    <% if @cliente.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>
  
        <ul>
          <% cliente.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control" %>
    </div>

    <div class="field form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class:"form-control" %>
    </div>
  
  
    <br>
    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>

<% end %>

<br>
<%= link_to 'Show', @cliente, class:"btn btn-primary" %> 
<%= link_to 'Back', clientes_path, class:"btn btn-primary" %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table class="table table-bordered">
  <thead class="table table-dark">
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Usuario</th>
      <th>Saldo</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nome %></td>
        <td><%= cliente.email %></td>
        <td><%= cliente.usuario %></td>
        <td><%= cliente.saldo %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Edit Password', edit_password_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Cliente', new_cliente_path, class:"btn btn-primary" %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>
<br>
<%= link_to 'Back', clientes_path, class:"btn btn-primary" %>

app/views/clientes/saldo.html.erb
<%= form_with(model: cliente) do |form| %>
    <% if cliente.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>
  
        <ul>
          <% cliente.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field form-group">
      <%= form.label :nome %>
      <%= form.text_field :nome, class:"form-control" %>
    </div>
  
    <div class="field form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class:"form-control" %>
    </div>
  
    <div class="field form-group">
      <%= form.label :usuario %>
      <%= form.text_field :usuario, class:"form-control" %>
    </div>
  
    <div class="field form-group">
      <%= form.label :password %>
      <%= form.password_field :password, class:"form-control" %>
    </div>
  
    <div class="field form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field :password_confirmation, class:"form-control" %>
    </div>
  
    <div class="field form-group">
      <%= form.label :saldo %>
      <%= form.number_field :saldo, class:"form-control" %>
    </div>
  
    <br>
    <div class="actions">
      <%= form.submit class:"btn btn-primary" %>
    </div>
  <% end %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @cliente.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @cliente.email %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @cliente.usuario %>
</p>


<p>
  <strong>Saldo:</strong>
  <%= @cliente.saldo %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> 
<%= link_to 'Back', clientes_path %>