config/routes.rb
Rails.application.routes.draw do
  resources :pontos
  resources :trocas
  resources :produtos
  resources :clientes do
    member do
      get 'edit_password'
      patch 'update_password'
    end 
  end
  devise_for :funcionarios, path: 'auth'
  resources :funcionarios
  resources :categorias
  root "application#index"

  scope :api, defaults: { format: :json } do
    devise_for :clientes,
      controllers: {
        sessions: 'api/sessions',
        passwords: 'api/passwords'
      }
  end
  namespace :api do
    resources :clientes, only: [:update] do
      member do
        patch 'update_password'
      end
      collection do
        get 'token'
      end
    end
    resources :trocas, only: [:create, :index] do
      member do
        put 'cancelar'
      end
    end
    resources :produtos, only: [:index]
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/produto.rb
class Produto < ApplicationRecord
  mount_uploader :foto, FotoUploader
  
  validates :nome, :preco, presence: true
  belongs_to :categoria

  def self.search(params)
    produtos = joins(:categoria)
    produtos = produtos.where("produtos.nome LIKE ?", "%#{params[:nome]}%") unless params[:nome].blank?
    produtos = produtos.where("produtos.descricao LIKE ?", "%#{params[:descricao]}%") unless params[:descricao].blank?
    produtos = produtos.where("categorias.nome LIKE ?", "%#{params[:categoria]}%") unless params[:categoria].blank?
    return produtos
  end

end

app/controllers/api/produtos_controller.rb
class Api::ProdutosController < ApiController
    def index
        render json: Produto.search(params), status: :ok
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: %i[ show edit update destroy ]

  # GET /produtos or /produtos.json
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1 or /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
    @categorias = Categoria.all
  end

  # GET /produtos/1/edit
  def edit
    @categorias = Categoria.all
  end

  # POST /produtos or /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: "Produto was successfully created." }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1 or /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: "Produto was successfully updated." }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1 or /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: "Produto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :foto, :categoria_id, :preco)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_with(model: produto) do |form| %>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
        <% produto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :descricao %>
    <%= form.text_area :descricao, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :foto %>
    <%= form.file_field :foto, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :categoria_id %>
    <%= form.select :categoria_id, Categoria.all.collect {|c| [c.nome, c.id] }, {include_blank: true}, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :preco %>
    <%= form.number_field :preco, class:"form-control" %>
  </div>

  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editing Produto</h1>

<%= render 'form', produto: @produto %>
<br>
<%= link_to 'Show', @produto, class:"btn btn-primary" %> 
<%= link_to 'Back', produtos_path, class:"btn btn-primary" %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Produtos</h1>

<table class="table table-bordered">
  <thead class="table table-dark">
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Categoria</th>
      <th>Preço</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.nome %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.categoria.try(:nome) %></td>
        <td><%= produto.preco %></td>
        <td><%= link_to 'Show', produto %></td>
        <td><%= link_to 'Edit', edit_produto_path(produto) %></td>
        <td><%= link_to 'Destroy', produto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Produto', new_produto_path, class:"btn btn-primary" %>

app/views/produtos/new.html.erb
<h1>New Produto</h1>

<%= render 'form', produto: @produto %>
<br>
<%= link_to 'Back', produtos_path, class:"btn btn-primary" %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @produto.nome %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<% unless @produto.foto.file.nil? %>
  <p>
  <strong>Foto:</strong>
  <%= image_tag @produto.foto.url, style: "max-width: 200px; max-height: 200px;" %>
  </p>
<% end %>

<p>
  <strong>Categoria:</strong>
  <%= @produto.categoria.try(:nome) %>
</p>
<p>
  <strong>Preço:</strong>
  <%= @produto.preco %>
</p>

<%= link_to 'Edit', edit_produto_path(@produto) %> |
<%= link_to 'Back', produtos_path %>