config/routes.rb
Rails.application.routes.draw do
  resources :pontos
  resources :trocas
  resources :produtos
  resources :clientes do
    member do
      get 'edit_password'
      patch 'update_password'
    end 
  end
  devise_for :funcionarios, path: 'auth'
  resources :funcionarios
  resources :categorias
  root "application#index"

  scope :api, defaults: { format: :json } do
    devise_for :clientes,
      controllers: {
        sessions: 'api/sessions',
        passwords: 'api/passwords'
      }
  end
  namespace :api do
    resources :clientes, only: [:update] do
      member do
        patch 'update_password'
      end
      collection do
        get 'token'
      end
    end
    resources :trocas, only: [:create, :index] do
      member do
        put 'cancelar'
      end
    end
    resources :produtos, only: [:index]
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/funcionario.rb
class Funcionario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  enum papel: [:admin, :user]
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :set_funcionario, only: %i[ show edit update destroy ]

  # GET /funcionarios or /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1 or /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios or /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: "Funcionario was successfully created." }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1 or /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: "Funcionario was successfully updated." }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1 or /funcionarios/1.json
  def destroy
    @funcionario.destroy
    respond_to do |format|
      format.html { redirect_to funcionarios_url, notice: "Funcionario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :email, :password, :password_confirmation, :papel)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_with(model: funcionario) do |form| %>
  <% if funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
        <% funcionario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nome %>
    <%= form.text_field :nome, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.email_field :email, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :papel %>
    <%= form.select :papel,  [[:admin]], {prompt: "Selecione"}, class:"form-control" %>
  </div>


  <div class="field form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control" %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editing Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>
<br>
<%= link_to 'Show', @funcionario, class:"btn btn-primary" %> 
<%= link_to 'Back', funcionarios_path, class:"btn btn-primary" %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Funcionarios</h1>

<table class="table table-bordered">
  <thead class="table table-dark">
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Papel</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <td><%= funcionario.nome %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.papel %></td>
        <td><%= link_to 'Show', funcionario %></td>
        <td><%= link_to 'Edit', edit_funcionario_path(funcionario) %></td>
        <td><%= link_to 'Destroy', funcionario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '+ New Funcionario', new_funcionario_path, class:"btn btn-primary" %>

app/views/funcionarios/new.html.erb
<h1>New Funcionario</h1>

<%= render 'form', funcionario: @funcionario %>
<br>
<%= link_to 'Back', funcionarios_path, class:"btn btn-primary" %>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>




<%= link_to 'Edit', edit_funcionario_path(@funcionario) %> |
<%= link_to 'Back', funcionarios_path %>