config/routes.rb
Rails.application.routes.draw do
  resources :pontos
  resources :trocas
  resources :produtos
  resources :clientes do
    member do
      get 'edit_password'
      patch 'update_password'
    end 
  end
  devise_for :funcionarios, path: 'auth'
  resources :funcionarios
  resources :categorias
  root "application#index"

  scope :api, defaults: { format: :json } do
    devise_for :clientes,
      controllers: {
        sessions: 'api/sessions',
        passwords: 'api/passwords'
      }
  end
  namespace :api do
    resources :clientes, only: [:update] do
      member do
        patch 'update_password'
      end
      collection do
        get 'token'
      end
    end
    resources :trocas, only: [:create, :index] do
      member do
        put 'cancelar'
      end
    end
    resources :produtos, only: [:index]
  end

end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>Shopping Points</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Shopping", root_path, class:"navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_funcionario%>
      
        <%= link_to "Categorias", categorias_path, class:"navbar-brand"%>
        <%= link_to "Funcionários", funcionarios_path, class:"navbar-brand"%>
        <%= link_to "Clientes", clientes_path, class:"navbar-brand"%>
        <%= link_to "Produtos", produtos_path, class:"navbar-brand"%>
        <%= link_to "Trocas",  trocas_path, class:"navbar-brand"%>
        <%= link_to "Pontos",  pontos_path, class:"navbar-brand"%>

        
        <a class="st" href="/"><%= current_funcionario.nome%></a>
        
        <%= link_to "Sair", destroy_funcionario_session_path, method: :delete, class:"navbar-brand st2" %></li>
   </ul>  
        <% end %>    
    </form>
  </div>
</nav>

  <div class="container">
    <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>